config/routes.rb
Rails.application.routes.draw do
  devise_for :unit_owners, controllers: {
    invitations: 'unit_owners/invitations'
  }

  devise_for :admin_users, controllers: {
    registrations: 'admin_users/registrations',
    sessions: 'admin_users/sessions',
    # omniauth_callbacks: 'admin_users/omniauth_callbacks',
    # invitations: 'admin_users/invitations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  scope module: :admin, path: '/a' do
    get 'dashboard/index'

    namespace :unit_owner do
      resources :units do
        resources :invitations, only: %i[new create]
      end
    end

    namespace :onboarding, path: 'onboarding' do
      resources :account_details, only: %i[new create]
      resources :admin_user_profiles, only: %i[new create]
    end

    resources :apartments do
      resources :floors, except: %i[index]
    end
    resources :units
    resources :unit_owners, only: %i[index show]
    resources :checklist_items

  end

  namespace :unit_owners do
    resources :invitations, only: [:new, :create]
  end

  scope module: :tenant, path: '/t' do
    get 'dashboard/index'

    namespace :onboarding, path: 'onboarding' do
      resources :owner_informations, except: %i[index destroy]
      resources :checklists, only: %i[index]
    end
  end
end

app/models/unit.rb
# == Schema Information
#
# Table name: units
#
#  id           :bigint           not null, primary key
#  cost         :decimal(, )      default(0.0), not null
#  name         :string           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  floor_id     :bigint           not null
#  unit_type_id :bigint           not null
#
# Indexes
#
#  index_units_on_floor_id      (floor_id)
#  index_units_on_name          (name)
#  index_units_on_unit_type_id  (unit_type_id)
#
# Foreign Keys
#
#  fk_rails_...  (floor_id => floors.id)
#  fk_rails_...  (unit_type_id => unit_types.id)
#
class Unit < ApplicationRecord
  include Comboboxable

  belongs_to :floor
  belongs_to :unit_type
  has_many :lease_agreements
  has_many :unit_owners, through: :lease_agreements
  has_many :unit_payments

end

app/models/unit_type.rb
# == Schema Information
#
# Table name: unit_types
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class UnitType < ApplicationRecord
  include Comboboxable

  has_many :units

end

app/controllers/admin/units_controller.rb
class Admin::UnitsController < Admin::BaseController
  before_action :set_unit, only: %i[show edit update destroy]
  before_action :set_filter, only: %i[index]

  def index
    @pagy, @units = pagy(@filter.scope.latest)
  end

  def new
    @unit = Unit.new
  end

  def show
    @unit_owners = @unit.unit_owners.order(created_at: :desc)
  end

  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html {redirect_to request.referrer, notice: "Unit added successfully" }
        # format.turbo_stream
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html {redirect_to request.referrer, notice: "Unit updated successfully" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @unit.destroy
    redirect_to units_path, alert: 'Unit Deleted Successfully'
  end

  private

  def unit_params
    params.require(:unit).permit(:name, :unit, :floor_id, :unit_type_id)
  end

  def set_unit
    @unit = Unit.find(params[:id])
  end

  def set_filter
    @filter = params[:filter].present? ? UnitFilter.find(params[:filter]) : UnitFilter.new
    @filter.update(filter_params)
    @filter.update(current_account_id: current_account.id)
  end

  def filter_params
    params.permit(:search, :floor_id, :current_account_id)
  end

end

app/views/admin/units/_filter.html.erb
<%= form_with(url: units_path, method: :get, data: { turbo_frame: "units-table"}) do |form| %>
	<%#= form.hidden_field :filter, value: @filter.id %>
  <%#= form.hidden_field :current_account_id, value: current_account.id %>
  <div class="relative">
    <label for="hs-as-table-product-review-search" class="sr-only">Search</label>
    <%= form.search_field :search, id: "hs-as-table-product-review-search", placeholder: "Search", oninput: "this.form.requestSubmit()", class: "py-2 px-3 block w-full border border-gray-200 rounded-lg text-sm disabled:opacity-50 disabled:pointer-events-none shadow-md" %>
  </div>
<% end %>

app/views/admin/units/_form.html.erb
<div>
  <%= form_with(model: [floor, unit], data: { turbo_frame: '_top'}) do |form| %>
    <div>
      <%= form.label :name, class: "block text-sm font-medium mb-2 " %>
      <%= form.text_field :name, class: "py-3 px-4 block w-full border border-gray-300 rounded-lg text-sm focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none border-gray-700 dark:focus:ring-gray-600" %>
    </div>

    <div>
      <%= form.label :floor_id, class: "block text-sm font-medium mb-2" %>
      <%= form.combobox :floor_id, current_account.floors %>
    </div>

    <div>
      <%= form.label :unit_type_id, class: "block text-sm font-medium mb-2" %>
      <%= form.combobox :unit_type_id, UnitType.all %>
    </div>

    <div class="mt-4">
      <%= link_to "Cancel", units_path, data: { turbo_frame: "_top" }, class: "py-3 px-4 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-50 disabled:pointer-events-none dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600"%>
      <%= form.submit class: "py-3 px-4 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-50 disabled:pointer-events-none dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600" %>
    </div>
  <% end %>
</div>

app/views/admin/units/_unit.html.erb
<tr id="<%= unit.id %>">
  <td class="h-px w-px whitespace-nowrap">
    <div class="px-6 py-3">
      <span class="text-sm text-gray-600"><%= unit.name %></span>
    </div>
  </td>
  <td class="h-px w-px whitespace-nowrap">
    <div class="px-6 py-3">
      <span class="text-sm text-gray-600">Tenant</span>
    </div>
  </td>
  <td class="h-px w-px whitespace-nowrap">
    <div class="px-6 py-1.5">
      <div class="hs-dropdown relative inline-block [--placement:bottom-right]">
        <button id="hs-table-dropdown-1" type="button" class="hs-dropdown-toggle py-1.5 px-2 inline-flex justify-center items-center gap-2 rounded-lg text-gray-700 align-middle disabled:opacity-50 disabled:pointer-events-none focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-white focus:ring-blue-600 transition-all text-sm">
          <svg class="flex-shrink-0 w-4 h-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/><circle cx="5" cy="12" r="1"/></svg>
        </button>
        <div class="hs-dropdown-menu transition-[opacity,margin] duration hs-dropdown-open:opacity-100 opacity-0 hidden divide-y divide-gray-200 min-w-[10rem] z-10 bg-white shadow-2xl rounded-lg p-2 mt-2" aria-labelledby="hs-table-dropdown-1">
          <div class="py-2 first:pt-0 last:pb-0">
            <%= link_to unit_path(unit), data: {turbo_frame: "_top"}, class: "flex items-center gap-x-3 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500" do %>
                Show
            <% end %>
            <%= link_to edit_unit_path(unit), data: { turbo_frame: "modal"}, class: "flex items-center gap-x-3 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500" do %>
                Edit
            <% end %>
          </div>
          <div class="py-2 first:pt-0 last:pb-0">
            <%= link_to unit_path(floor_id: params[:id] ,id: unit.id), data: { turbo_frame: "_top", "turbo_method": :delete, turbo_confirm: "Are you sure?" }, class: "flex items-center gap-x-3 py-2 px-3 rounded-lg text-sm text-red-600 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500" do %>
                Delete
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </td>
</tr>

app/views/admin/units/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= turbo_frame_tag @unit do %>
    <div aria-labelledby="modal-title"
      aria-modal="true" class="fixed inset-0 z-50 overflow-y-auto bg-black/80" role="dialog">
      <div class="h-screen w-full relative flex items-center justify-center">
        <div class="shadow-xl max-w-2xl bg-white m-1 p-8 prose prose-indigo origin-bottom mx-auto dark:bg-slate-700 dark:text-slate-200 min-w-[600px] rounded-2xl animate-fade-in-up">
          <h1 id="modal-title" class="dark:text-slate-100">Create Apartment</h1>
          <%= render "form", floor: @floor, unit: @unit %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/admin/units/index.html.erb
<!-- Table Section -->
<div class="w-full px-4 sm:px-6 lg:px-8 mx-auto">
  <!-- Card -->
  <div class="flex flex-col">
    <div class="-m-1.5 overflow-x-auto">
      <div class="p-1.5 min-w-full inline-block align-middle">
        <div class="sm:flex-auto mb-4">
          <h1 class="text-2xl font-semibold text-gray-900">Units</h1>
			  </div>
        <div class="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden">
          <!-- Header -->
          <div class="px-6 py-4 grid gap-3 md:flex md:justify-between md:items-center border-b border-gray-200">
            <!-- Input -->
            <%= render "filter", apartment_id: params[:apartment_id], floor_id: params[:id] %>
            <!-- End Input -->

            <div>
              <div class="inline-flex gap-x-2">
                <a class="py-2 px-3 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none" href="#">
                  View all
                </a>

                <%= link_to new_unit_path, data: { turbo_frame: dom_id(Unit.new) }, class: "py-2 px-3 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-50 disabled:pointer-events-none"  do %>
                  <svg class="flex-shrink-0 size-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="M12 5v14"/></svg>
                  Add Unit
                <% end %>
              </div>
            </div>
          </div>
          <!-- End Header -->

          <%= turbo_frame_tag Unit.new %>
          <!-- Table -->
          <%= turbo_frame_tag "units-table" do %>
            <table class="min-w-full divide-y divide-gray-200">
              <thead class="bg-gray-50">
                <tr>
                  <th scope="col" class="px-6 py-3 text-start">
                    <div class="flex items-center gap-x-2">
                      <span class="text-xs font-semibold uppercase tracking-wide text-gray-800">
                        Unit Name
                      </span>
                    </div>
                  </th>

                  <th scope="col" class="px-6 py-3 text-start">
                    <div class="flex items-center gap-x-2">
                      <span class="text-xs font-semibold uppercase tracking-wide text-gray-800">
                      Tenant
                      </span>
                    </div>
                  </th>
                  <th scope="col" class="px-6 py-3 text-end"></th>
                </tr>
              </thead>
                  <tbody id="units">
                      <%= render @units %>
                  </tbody>
            </table>
          <% end %>
          <!-- End Table -->          
          <%== render partial: 'shared/pagination/pagy', locals: {pagy: @pagy, model: "Unit"} %>
        </div>
      </div>
    </div>
  </div>
  <!-- End Card -->
</div>
<!-- End Table Section -->

app/views/admin/units/new.html.erb
<%= turbo_frame_tag "new_unit" do %>
  <%= turbo_frame_tag "modal" do %>
  <%= @floor %>
    <div aria-labelledby="modal-title"
      aria-modal="true" class="fixed inset-0 z-50 overflow-y-auto bg-black/80" role="dialog">
      <div class="h-screen w-full relative flex items-center justify-center">
        <div class="shadow-xl max-w-2xl bg-white m-1 p-8 prose prose-indigo origin-bottom mx-auto dark:bg-slate-700 dark:text-slate-200 min-w-[600px] rounded-2xl animate-fade-in-up">
          <h1 id="modal-title" class="dark:text-slate-100">Create Unit</h1>
          <%= render "form", floor: @floor, unit: @unit %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/admin/units/show.html.erb
<!-- Unit Details Page -->
<div class="w-full px-4 py-10 sm:px-6 lg:px-8 lg:py-14 mx-auto">
  <div class="flex flex-col  bg-gray-50 border shadow-sm rounded-xl">
    <div class="p-4 md:px-8 md:py-12 grid grid-cols-4 gap-x-4">
      <div class="flex flex-col gap-x-2 space-y-4">
        <div>
           <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="m2.25 12 8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
          </svg>
        </div>
        <div class="flex flex-col space-y-2">
          <p class="text-xs uppercase tracking-wide text-gray-500">
            Unit Name
          </p>
          <div class="">
              <%= @unit.name %>
          </div>
        </div>
      </div>

      <div class="flex flex-col gap-x-2 space-y-4">
        <div>
           <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 5.25h16.5m-16.5 4.5h16.5m-16.5 4.5h16.5m-16.5 4.5h16.5" />
          </svg>
        </div>
        <div class="flex flex-col space-y-2">
          <p class="text-xs uppercase tracking-wide text-gray-500">
            Floor No.
          </p>
          <div class="">
              <%= @unit.floor.name %>
          </div>
        </div>
      </div>

      <div class="flex flex-col gap-x-2 space-y-4">
        <div>
           <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 4h12M6 4v16M6 4H5m13 0v16m0-16h1m-1 16H6m12 0h1M6 20H5M9 7h1v1H9V7Zm5 0h1v1h-1V7Zm-5 4h1v1H9v-1Zm5 0h1v1h-1v-1Zm-3 4h2a1 1 0 0 1 1 1v4h-4v-4a1 1 0 0 1 1-1Z"/>
          </svg>
        </div>
        <div class="flex flex-col space-y-2">
          <p class="text-xs uppercase tracking-wide text-gray-500">
            Apartment Name
          </p>
          <div class="">
              <%= @unit.floor.apartment.name %>
          </div>
        </div>
      </div>

      <div class="flex flex-col gap-x-2 space-y-4">
        <div class="flex items-start">
           <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M9.568 3H5.25A2.25 2.25 0 0 0 3 5.25v4.318c0 .597.237 1.17.659 1.591l9.581 9.581c.699.699 1.78.872 2.607.33a18.095 18.095 0 0 0 5.223-5.223c.542-.827.369-1.908-.33-2.607L11.16 3.66A2.25 2.25 0 0 0 9.568 3Z" />
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 6h.008v.008H6V6Z" />
          </svg>
        </div>
        <div class="flex flex-col space-y-2">
          <p class="text-xs uppercase tracking-wide text-gray-500">
            Residential Location
          </p>
          <div class="">
              <%= @unit.floor.apartment.location %>
          </div>
        </div>
      </div>
    </div>
  </div>
<div>
<!-- Table Section -->
<div class="w-full lg:py-14 mx-auto">
  <!-- Card -->
  <div class="flex flex-col">
    <div class="overflow-x-auto">
      <div class="p-1.5 min-w-full inline-block align-middle">
        <div class="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden">
          <!-- Header -->
          <div class="px-6 py-4 grid gap-3 md:flex md:justify-between md:items-center border-b border-gray-200">
            <div>
              <h2 class="text-xl font-semibold text-gray-800">
                <%= @unit.name %> Owners
              </h2>
            </div>

            <div>
              <div class="inline-flex gap-x-2">
                <a class="py-2 px-3 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none" href="#">
                  View all
                </a>

                <%= link_to new_unit_owner_unit_invitation_path(unit_id: @unit.id), data: { turbo_frame: dom_id(UnitOwner.new) }, class: "py-2 px-3 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-50 disabled:pointer-events-none"  do %>
                  <svg class="flex-shrink-0 size-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="M12 5v14"/></svg>
                  Add Tenant
                <% end %>
              </div>
            </div>
          </div>
          <!-- End Header -->

          <%= turbo_frame_tag UnitOwner.new %>
          <!-- Table -->
          <table class="w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="px-6 py-3 text-start">
                  <div class="flex items-center gap-x-2">
                    <span class="text-xs font-semibold uppercase tracking-wide text-gray-800">
                      Name
                    </span>
                  </div>
                </th>

                <th scope="col" class="px-6 py-3 text-start">
                  <div class="flex items-center gap-x-2">
                    <span class="text-xs font-semibold uppercase tracking-wide text-gray-800">
                      Email
                    </span>
                  </div>
                </th>

                <th scope="col" class="px-6 py-3 text-start">
                  <div class="flex items-center gap-x-2">
                    <span class="text-xs font-semibold uppercase tracking-wide text-gray-800">
                      Status
                    </span>
                  </div>
                </th>
                <th scope="col" class="px-6 py-3 text-end"></th>
              </tr>
            </thead>

            <tbody id="unit_owners" class="divide-y divide-gray-200">
              <%= render @unit_owners %>
            </tbody>
          </table>
          <!-- End Table -->

          <!-- Footer -->
          <div class="px-6 py-4 grid gap-3 md:flex md:justify-between md:items-center border-t border-gray-200">
            <div>
              <p class="text-sm text-gray-600 dark:text-neutral-400">
                <span class="font-semibold text-gray-800">6</span> results
              </p>
            </div>

            <div>
              <div class="inline-flex gap-x-2">
                <button type="button" class="py-2 px-3 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none">
                  <svg class="flex-shrink-0 size-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m15 18-6-6 6-6"/></svg>
                  Prev
                </button>

                <button type="button" class="py-2 px-3 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none">
                  Next
                  <svg class="flex-shrink-0 size-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m9 18 6-6-6-6"/></svg>
                </button>
              </div>
            </div>
          </div>
          <!-- End Footer -->
        </div>
      </div>
    </div>
  </div>
  <!-- End Card -->
</div>
<!-- End Table Section -->