config/routes.rb
Rails.application.routes.draw do
  devise_for :unit_owners, controllers: {
    invitations: 'unit_owners/invitations'
  }

  devise_for :admin_users, controllers: {
    registrations: 'admin_users/registrations',
    sessions: 'admin_users/sessions',
    # omniauth_callbacks: 'admin_users/omniauth_callbacks',
    # invitations: 'admin_users/invitations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  scope module: :admin, path: '/a' do
    get 'dashboard/index'

    namespace :unit_owner do
      resources :units do
        resources :invitations, only: %i[new create]
      end
    end

    namespace :onboarding, path: 'onboarding' do
      resources :account_details, only: %i[new create]
      resources :admin_user_profiles, only: %i[new create]
    end

    resources :apartments do
      resources :floors, except: %i[index]
    end
    resources :units
    resources :unit_owners, only: %i[index show]
    resources :checklist_items

  end

  namespace :unit_owners do
    resources :invitations, only: [:new, :create]
  end

  scope module: :tenant, path: '/t' do
    get 'dashboard/index'

    namespace :onboarding, path: 'onboarding' do
      resources :owner_informations, except: %i[index destroy]
      resources :checklists, only: %i[index]
    end
  end
end

app/controllers/admin/onboarding/account_details_controller.rb
module Admin
  class Onboarding::AccountDetailsController < Onboarding::BaseController

    def new
      @account = Account.new
    end

    def create
      @account = Account.new(account_params)
      
      if @account.save
        AdminUser.set_user_account(account_id: @account.id )
        redirect_to new_onboarding_admin_user_profile_path, notice: "Account Created Successfully"
      else
        render :new, status: :unprocessable_entity
      end
    end

    private

    def account_params
      params.require(:account).permit(:company_email, :company_name, :contact_person_name, :address)
    end
  end
end

app/controllers/admin/onboarding/admin_user_profiles_controller.rb
module Admin
  class Onboarding::AdminUserProfilesController < Onboarding::BaseController
    
    def new
      @admin_user_profile = current_admin_user.build_admin_user_profile
    end

    def create
      @admin_user = current_admin_user.build_admin_user_profile(admin_user_profile_params)
      
        if @admin_user.save
          redirect_to dashboard_index_path, notice: "Onboarding completed Successfully"
        else
          render :new, status: :unprocessable_entity
        end
    end

    private

    def admin_user_profile_params
      params.require(:admin_user_profile).permit(:first_name, :surname, :phone)
    end
  end
end

app/controllers/admin/onboarding/base_controller.rb
module Admin
  class Onboarding::BaseController < Admin::BaseController
    before_action :authenticate_admin_user!
    layout 'onboarding/base'
  end
end

app/controllers/tenant/onboarding/base_controller.rb
module Tenant
  class Onboarding::BaseController < Tenant::BaseController
    before_action :authenticate_unit_owner!
    layout 'onboarding/base'
  end
end

app/controllers/tenant/onboarding/checklists_controller.rb
module Tenant
  class Onboarding::ChecklistsController < Onboarding::BaseController

    def new
      @checklist = Checklist.new
    end

    def create
      @checklist = Checklist.new(owner_informations_params)

      respond_to do |format|
        if @checklist.save
          format.html { redirect_to '/t/dashboard/index', notice: "Profile updated successfully" }
        else
          format.html { render :edit, status: :unprocessable_entity}
        end
      end
    end

    private

    def checklist_params
      params.require(:checklist).permit()
    end
  end
end

app/controllers/tenant/onboarding/owner_informations_controller.rb
module Tenant
  class Onboarding::OwnerInformationsController < Onboarding::BaseController
    before_action :set_owner_information, only: %i[edit update]

    def new
      @owner_information = OwnerInformation.new
    end

    def create
      @owner_information = current_unit_owner.build_owner_information(owner_informations_params)

      respond_to do |format|
        if @owner_information.save
          format.html { redirect_to onboarding_checklists_path, notice: "Profile updated successfully" }
        else
          format.html { render :edit, status: :unprocessable_entity}
        end
      end
    end

    def edit; end

    # Update method will need to change as the flow has changed
    def update
      respond_to do |format|
        if @owner_information.update(owner_informations_params)
          format.html { redirect_to '/t/dashboard/index', notice: "Profile updated successfully" }
        else
          format.html { render :edit, status: :unprocessable_entity}
        end
      end
    end

    private

    def set_owner_information
      @owner_information = current_unit_owner.owner_informations.find(params[:id])
    end

    def owner_informations_params
      params.require(:owner_information).permit(:first_name, :middle_name, :surname, :phone, :gender, :avatar)
    end
  end
end

app/views/admin/onboarding/admin_user_details/_form.html.erb
<div>
  <h1 class="text-3xl font-bold leading-6 mb-6">Landlord Details </h1>
  <%= form_with(model: @admin_user, url: onboarding_admin_user_details_path, method: :post) do |form| %>
    <%= form.hidden_field :account_id, value: account_id %>
    <div>
      <%= form.label :first_name, class: "block text-sm font-medium mb-2 " %>
      <%= form.text_field :first_name, class: "py-3 px-4 block w-full border border-gray-300 rounded-lg text-sm focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none border-gray-700 dark:focus:ring-gray-600" %>
    </div>

    <div>
      <%= form.label :surname, class: "block text-sm font-medium mb-2 " %>
      <%= form.text_field :surname, class: "py-3 px-4 block w-full border border-gray-300 rounded-lg text-sm focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none border-gray-700 dark:focus:ring-gray-600" %>
    </div>

    <div>
      <%= form.label :phone, class: "block text-sm font-medium mb-2 " %>
      <%= form.text_field :phone, class: "py-3 px-4 block w-full border border-gray-300 rounded-lg text-sm focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none border-gray-700 dark:focus:ring-gray-600" %>
    </div>

    <div class="mt-4">
      <%= form.submit "Complete Onboarding", class: "py-3 px-4 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-50 disabled:pointer-events-none dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600" %>
    </div>
  <% end %>
</div>