config/routes.rb
Rails.application.routes.draw do
  devise_for :unit_owners, controllers: {
    invitations: 'unit_owners/invitations'
  }

  devise_for :admin_users, controllers: {
    registrations: 'admin_users/registrations',
    sessions: 'admin_users/sessions',
    # omniauth_callbacks: 'admin_users/omniauth_callbacks',
    # invitations: 'admin_users/invitations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  scope module: :admin, path: '/a' do
    get 'dashboard/index'

    namespace :unit_owner do
      resources :units do
        resources :invitations, only: %i[new create]
      end
    end

    namespace :onboarding, path: 'onboarding' do
      resources :account_details, only: %i[new create]
      resources :admin_user_profiles, only: %i[new create]
    end

    resources :apartments do
      resources :floors, except: %i[index]
    end
    resources :units
    resources :unit_owners, only: %i[index show]
    resources :checklist_items

  end

  namespace :unit_owners do
    resources :invitations, only: [:new, :create]
  end

  scope module: :tenant, path: '/t' do
    get 'dashboard/index'

    namespace :onboarding, path: 'onboarding' do
      resources :owner_informations, except: %i[index destroy]
      resources :checklists, only: %i[index]
    end
  end
end

app/models/floor.rb
# == Schema Information
#
# Table name: floors
#
#  id           :bigint           not null, primary key
#  name         :string           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  apartment_id :bigint           not null
#
# Indexes
#
#  index_floors_on_apartment_id  (apartment_id)
#  index_floors_on_name          (name)
#
# Foreign Keys
#
#  fk_rails_...  (apartment_id => apartments.id)
#
class Floor < ApplicationRecord
  include Comboboxable

  belongs_to :apartment
  with_options dependent: :destroy do
    has_many :units
  end

end

app/controllers/admin/floors_controller.rb
class Admin::FloorsController < Admin::BaseController
  before_action :set_apartment
  before_action :set_floor, only: %i[show edit update destroy]
  before_action :set_filter, only: %i[show]

  def new
    @floor = @current_apartment.floors.build
  end

  def show
    @pagy, @units = pagy(@filter.scope.latest)
  end

  def create
    @floor = @current_apartment.floors.build(floor_params)

    respond_to do |format|
      if @floor.save
        format.html {redirect_to apartment_path(@current_apartment), notice: "Floor added successfully" }
        # format.turbo_stream
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @floor.update(floor_params)
        format.html { redirect_to apartment_path(@current_apartment), notice: "Floor updated successfully" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @floor.destroy
    redirect_to apartment_path(@current_apartment), alert: 'Floor Deleted Successfully'
  end

  private

  def floor_params
    params.require(:floor).permit(:name)
  end

  def set_floor
    @floor = @current_apartment.floors.find(params[:id])
  end

  def set_apartment
    @current_apartment = Apartment.find(params[:apartment_id])
  end

  def set_filter
    @filter = params[:filter].present? ? UnitFilter.find(params[:filter]) : UnitFilter.new
    @filter.update(filter_params)
    @filter.update(floor_id: params[:id]) if params[:id].present?
  end

  def filter_params
    params.permit(:search, :floor_id)
  end

end

app/views/admin/floors/_filter.html.erb
<%= form_with(url: apartments_path, method: :get, data: { turbo_frame: "apartments-table"}) do |form| %>
	<%#= form.hidden_field :filter, value: @filter.id %>
  <%= form.hidden_field :current_account_id, value: current_account.id %>
  <div class="relative">
    <label for="hs-as-table-product-review-search" class="sr-only">Search</label>
    <%= form.search_field :search, id: "hs-as-table-product-review-search", placeholder: "Search", oninput: "this.form.requestSubmit()", class: "py-2 px-3 block w-full border border-gray-200 rounded-lg text-sm disabled:opacity-50 disabled:pointer-events-none shadow-md" %>
  </div>
<% end %>

app/views/admin/floors/_floor.html.erb
<tr id="<%= floor.id %>">
  <td class="h-px w-px whitespace-nowrap">
    <div class="px-6 py-3">
      <span class="text-sm text-gray-600"><%= floor.name %></span>
    </div>
  </td>

    <td class="h-px w-px whitespace-nowrap">
        <div class="px-6 py-3">
            <span class="text-sm text-gray-600">No of Units</span>
        </div>
    </td>

  <td class="h-px w-px whitespace-nowrap">
    <div class="px-6 py-1.5">
      <div class="hs-dropdown relative inline-block [--placement:bottom-right]">
        <button id="hs-table-dropdown-1" type="button" class="hs-dropdown-toggle py-1.5 px-2 inline-flex justify-center items-center gap-2 rounded-lg text-gray-700 align-middle disabled:opacity-50 disabled:pointer-events-none focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-white focus:ring-blue-600 transition-all text-sm">
          <svg class="flex-shrink-0 w-4 h-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/><circle cx="5" cy="12" r="1"/></svg>
        </button>
        <div class="hs-dropdown-menu transition-[opacity,margin] duration hs-dropdown-open:opacity-100 opacity-0 hidden divide-y divide-gray-200 min-w-[10rem] z-10 bg-white shadow-2xl rounded-lg p-2 mt-2" aria-labelledby="hs-table-dropdown-1">
          <div class="py-2 first:pt-0 last:pb-0">
            <%= link_to apartment_floor_path(apartment_id: params[:id] ,id: floor.id), data: {turbo_frame: "_top"}, class: "flex items-center gap-x-3 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500" do %>
                Show
            <% end %>
            <%= link_to edit_apartment_floor_path(apartment_id: params[:id] ,id: floor.id), data: { turbo_frame: "modal"}, class: "flex items-center gap-x-3 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500" do %>
                Edit
            <% end %>
          </div>
          <div class="py-2 first:pt-0 last:pb-0">
            <%= link_to apartment_floor_path(apartment_id: params[:id] ,id: floor.id), data: { turbo_frame: "_top", "turbo_method": :delete, turbo_confirm: "Are you sure?" }, class: "flex items-center gap-x-3 py-2 px-3 rounded-lg text-sm text-red-600 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500" do %>
                Delete
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </td>
</tr>

app/views/admin/floors/_form.html.erb
<div>
  <%= form_with(model: [apartment, floor], data: { turbo_frame: '_top'}) do |form| %>
    <div>
      <%= form.label :name, class: "block text-sm font-medium mb-2 " %>
      <%= form.text_field :name, class: "py-3 px-4 block w-full border border-gray-300 rounded-lg text-sm focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none border-gray-700 dark:focus:ring-gray-600" %>
    </div>

    <div class="mt-4">
      <%= link_to "Cancel", apartment_path(apartment), data: { turbo_frame: "_top" }, class: "py-3 px-4 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-50 disabled:pointer-events-none dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600"%>
      <%= form.submit class: "py-3 px-4 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-50 disabled:pointer-events-none dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600" %>
    </div>
  <% end %>
</div>

app/views/admin/floors/create.turbo_stream.erb
<%= turbo_stream.prepend "floors", @floor %>
<%= turbo_stream.update Floor.new, "" %>

app/views/admin/floors/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= turbo_frame_tag @floor do %>
    <div aria-labelledby="modal-title"
      aria-modal="true" class="fixed inset-0 z-50 overflow-y-auto bg-black/80" role="dialog">
      <div class="h-screen w-full relative flex items-center justify-center">
        <div class="shadow-xl max-w-2xl bg-white m-1 p-8 prose prose-indigo origin-bottom mx-auto dark:bg-slate-700 dark:text-slate-200 min-w-[600px] rounded-2xl animate-fade-in-up">
          <h1 id="modal-title" class="dark:text-slate-100">Create Apartment</h1>
          <%= render "form", apartment: @current_apartment, floor: @floor %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/admin/floors/show.html.erb
<!-- Table Section -->
<div class="w-full px-4 sm:px-6 lg:px-8 mx-auto">
  <!-- Card -->
  <div class="flex flex-col">
    <div class="-m-1.5 overflow-x-auto">
      <div class="p-1.5 min-w-full inline-block align-middle">
        <div class="sm:flex-auto mb-4">
          <h1 class="text-2xl font-semibold text-gray-900">Units</h1>
			  </div>
        <div class="bg-white border-2 border-gray-200 rounded-xl shadow-sm overflow-hidden">
          <!-- Header -->
          <div class="px-6 py-4 grid gap-3 md:flex md:justify-between md:items-center border-b border-gray-200">
            <!-- Input -->
            <%= render "admin/floors/units/filter", apartment_id: params[:apartment_id], floor_id: params[:id] %>
            <!-- End Input -->

            <div>
              <div class="inline-flex gap-x-2">
                <a class="py-2 px-3 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none dark:bg-neutral-900" href="#">
                  View all
                </a>

                <%= link_to new_unit_path, data: { turbo_frame: dom_id(Unit.new) }, class: "py-2 px-3 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-50 disabled:pointer-events-none"  do %>
                  <svg class="flex-shrink-0 size-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="M12 5v14"/></svg>
                  Add Unit
                <% end %>
              </div>
            </div>
          </div>
          <!-- End Header -->

          <%= turbo_frame_tag Unit.new %>
          <!-- Table -->
          <%= turbo_frame_tag "units-table" do %>
            <table class="min-w-full divide-y divide-gray-200">
              <thead class="bg-gray-50">
                <tr>
                  <th scope="col" class="px-6 py-3 text-start">
                    <div class="flex items-center gap-x-2">
                      <span class="text-xs font-semibold uppercase tracking-wide text-gray-800">
                        Unit Name
                      </span>
                    </div>
                  </th>

                  <th scope="col" class="px-6 py-3 text-start">
                    <div class="flex items-center gap-x-2">
                      <span class="text-xs font-semibold uppercase tracking-wide text-gray-800">
                      Tenant
                      </span>
                    </div>
                  </th>
                  <th scope="col" class="px-6 py-3 text-end"></th>
                </tr>
              </thead>
                  <tbody id="units" class="divide-y divide-gray-200">
                      <%= render @units, floor: @floor, partial: 'admin/units/_unit' %>
                  </tbody>
            </table>
          <% end %>
          <!-- End Table -->          
          <%== render partial: 'shared/pagination/pagy', locals: {pagy: @pagy, model: "Unit"} %>


          <!-- Footer -->
          <!--
          <div class="px-6 py-4 grid gap-3 md:flex md:justify-between md:items-center border-t border-gray-200 dark:border-neutral-700">
            <div>
              <p class="text-sm text-gray-600 dark:text-neutral-400">
                <span class="font-semibold text-gray-800">6</span> results
              </p>
            </div>

            <div>
              <div class="inline-flex gap-x-2">
                <button type="button" class="py-2 px-3 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none dark:bg-neutral-900 dark:border-neutral-700 dark:text-white dark:hover:bg-neutral-800">
                  <svg class="flex-shrink-0 size-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m15 18-6-6 6-6"/></svg>
                  Prev
                </button>

                <button type="button" class="py-2 px-3 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none dark:bg-neutral-900 dark:border-neutral-700 dark:text-white dark:hover:bg-neutral-800">
                  Next
                  <svg class="flex-shrink-0 size-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m9 18 6-6-6-6"/></svg>
                </button>
              </div>
            </div>
          </div>
          -->
          <!-- End Footer -->
        </div>
      </div>
    </div>
  </div>
  <!-- End Card -->
</div>
<!-- End Table Section -->